### PR TITLE
EXT-80: customize horizon container for bsn plugin enablement

### PR DESCRIPTION
**Pull request by wolverineav**
Reviewer: @sarath-kumar 

 - additional step in RHOSP 12 deployment would be to execute the
   newly added script `horizon_container_workaround.sh`
 - this would customize the upstream horizon container to include
   BSN plugin and its `enable` files
 - previously required manual step to copy the `enable` files would 
   not be required

corresponding cherry-pick https://github.com/bigswitch/horizon-bsn/pull/109

### CODE REVIEW

**Comment by bsn-bot3** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/openstack_horizon_bsn_pull_req/144/

**Comment by wolverineav** [comment]
test fails for version bump. but since this change is for updating build scripts, version bump is not required. we would intentionally skip it.

**Comment by bsn-bot3** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/openstack_horizon_bsn_pull_req/146/

**Comment by sarath-kumar** [comment]
Changes LGTM
One comment, we would need to apply the OSP plugin convention to the 'tag', 'version' fields going forward. I suggest we adopt the same scheme we have been using  <OSP>.<BCF_Start>.<Minor>. So, the horizon tag should be '12.47.1', what do you think?

**Pull request merged**
