### PR TITLE
merge master to liberty

### PR DESCRIPTION
**Pull request by wolverineav**
Reviewer: @wolverineav @mmxiong

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/openstack_horizon_bsn_pull_req/85/

**Comment by brajneesh** [comment]
@wolverineav why are we merging angular changes to Liberty?

**Comment by wolverineav** [comment]
> why are we merging angular changes to Liberty?

they're dormant until enabled files are copied and enabled files for angular are moved to `future_enabled` directory until tested. so it shouldn't cause a problem - bosi won't pickup those changes.
for `horizon-bsn` i maintain just one branch - master. the stable branches are just copies for ease of maintaining versions. release specific enabling of dashboards is done via `bosi` :)

**Comment by brajneesh** [comment]
OK @wolverineav

**Pull request merged**
